# Generated by Django 5.1.2 on 2025-01-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like_created_at_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
